# Combine all data
This notebook combines the characterized shearzone data with the shearzone data from tunnels. \
Then, global coordinates are calculated for the entire dataset.

In [1]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.extend([
    'C:/Users/Haakon/OneDrive/Dokumenter/FORSKNING/mastersproject/src/mastersproject',
    'C:/Users/Haakon/OneDrive/Dokumenter/FORSKNING/mastersproject/src/mastersproject/GTS'
])

In [2]:
import numpy as np
import pandas as pd

import GTS as gts

In [7]:
cls = gts.ISCData()

In [8]:
# Characterized borehole structures
borehole_structures = cls._characterize_shearzones()

# Tunnel shearzone data
tunnel_structures = cls.tunnel_shearzone_data()

structures = pd.concat([
    borehole_structures,
    tunnel_structures],
    ignore_index=True, sort=False)

# Fill NaN-values in all columns to 0 except in column 'shearzone', for which we do nothing.
structures = structures.fillna(
    value={
        **{s: 0 for s in borehole_structures},
        **{'shearzone': np.nan}
    })

mapping = {'x': 'x', 'y': 'y', 'z': 'z', 'depth': 'depth',
           'upward_gradient': 'upward_gradient', 'azimuth': 'azimuth_bh'}
cls.bh_struc_to_global_coords(structures, **mapping)

# Shear-zone -- borehole data
shearzone_borehole = cls.shearzone_borehole_data()
shearzone_borehole = shearzone_borehole[shearzone_borehole['depth'].notna()]

In [18]:
structures

,depth,azimuth_struc,dip,aperture,type,borehole,x,y,z,length,...,shearzone,_trig_x,_trig_y,_trig_z,x_swiss,y_swiss,z_swiss,x_gts,y_gts,z_gts
0,1.76,239.29,86.44,1.89,Fracture,SBH3,667468.567,158885.383,1733.960,20.55,...,NaN,-0.174210,-0.980982,0.085591,667468.260391,158883.656472,1734.110640,68.260391,83.656472,34.110640
1,2.11,78.11,21.13,0.00,Fracture,PRP3,667468.390,158892.660,1733.100,32.33,...,NaN,-0.382879,0.821461,-0.422618,667467.582126,158894.393282,1732.208275,67.582126,94.393282,32.208275
2,2.26,252.34,77.18,1.83,Fracture,SBH3,667468.567,158885.383,1733.960,20.55,...,NaN,-0.174210,-0.980982,0.085591,667468.173286,158883.165981,1734.153435,68.173286,83.165981,34.153435
3,2.35,169.30,57.47,334.61,Minor ductile Shear-zone,FBS1,667466.424,158888.882,1732.782,44.80,...,NaN,-0.578330,0.621269,-0.528735,667465.064926,158890.341981,1731.539474,65.064926,90.341981,31.539474
4,2.54,134.77,59.79,10.06,Quartz,GEO3,667470.923,158912.008,1732.416,30.10,...,NaN,-0.671720,-0.000469,-0.740805,667469.216830,158912.006809,1730.534356,69.216830,112.006809,30.534356
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,0.00,155.84,64.72,0.00,0,VE,667418.560,158907.674,1734.916,0.00,...,S1_3,0.000000,1.000000,0.000000,667418.560000,158907.674000,1734.916000,18.560000,107.674000,34.916000
597,0.00,170.00,72.40,0.00,0,AU,667472.094,158906.617,1732.813,0.00,...,S3_1,0.000000,1.000000,0.000000,667472.094000,158906.617000,1732.813000,72.094000,106.617000,32.813000
598,0.00,168.00,74.50,0.00,0,VE,667422.420,158913.208,1733.608,0.00,...,S3_1,0.000000,1.000000,0.000000,667422.420000,158913.208000,1733.608000,22.420000,113.208000,33.608000
599,0.00,171.70,67.25,0.00,0,AU,667472.185,158910.025,1733.639,0.00,...,S3_2,0.000000,1.000000,0.000000,667472.185000,158910.025000,1733.639000,72.185000,110.025000,33.639000
600,0.00,160.00,71.00,0.00,0,VE,667425.125,158918.238,1733.762,0.00,...,S3_2,0.000000,1.000000,0.000000,667425.125000,158918.238000,1733.762000,25.125000,118.238000,33.762000